--Insert sample Users (20 prospective renters + 19 agents)
INSERT INTO Users (First_name, Last_name, Phone_number, Email, User_type) VALUES
  -- RDR2 characters as prospective renters
  ('Arthur','Morgan','555-0001','arthur.morgan@example.com','prospective_renter'),
  ('John','Marston','555-0002','john.marston@example.com','prospective_renter'),
  ('Dutch','van der Linde','555-0003','dutch.vanderlinde@example.com','prospective_renter'),
  ('Hosea','Matthews','555-0004','hosea.matthews@example.com','prospective_renter'),
  ('Sadie','Adler','555-0005','sadie.adler@example.com','prospective_renter'),
  ('Micah','Bell','555-0006','micah.bell@example.com','prospective_renter'),
  ('Charles','Smith','555-0007','charles.smith@example.com','prospective_renter'),
  ('Bill','Williamson','555-0008','bill.williamson@example.com','prospective_renter'),
  ('Javier','Escuella','555-0009','javier.escuella@example.com','prospective_renter'),
  ('Reverend','Swanson','555-0010','reverend.swanson@example.com','prospective_renter'),
  ('Uncle','(Unknown)','555-0011','uncle@example.com','prospective_renter'),
  ('Abigail','Roberts','555-0012','abigail.roberts@example.com','prospective_renter'),
  ('Jack','Marston','555-0013','jack.marston@example.com','prospective_renter'),
  ('Karen','Jones','555-0014','karen.jones@example.com','prospective_renter'),
  ('Tilly','Jackson','555-0015','tilly.jackson@example.com','prospective_renter'),
  ('Susan','Grimshaw','555-0016','susan.grimshaw@example.com','prospective_renter'),
  ('Molly','O''Shea','555-0017','molly.oshea@example.com','prospective_renter'),
  ('Leopold','Strauss','555-0018','leopold.strauss@example.com','prospective_renter'),
  ('Sean','MacGuire','555-0019','sean.macguire@example.com','prospective_renter'),
  ('Lenny','Summers','555-0020','lenny.summers@example.com','prospective_renter'),

  -- Tom Cruise film characters as agents
  ('Pete "Maverick"','Mitchell','555-0021','maverick@example.com','agent'),
  ('Tom','Kazansky','555-0022','tom.kazansky@example.com','agent'),
  ('Nick','Bradshaw','555-0023','nick.goose@example.com','agent'),
  ('Charlotte','Blackwood','555-0024','charlie.blackwood@example.com','agent'),
  ('Ethan','Hunt','555-0025','ethan.hunt@example.com','agent'),
  ('Luther','Stickell','555-0026','luther.stickell@example.com','agent'),
  ('Benji','Dunn','555-0027','benji.dunn@example.com','agent'),
  ('William','Brandt','555-0028','william.brandt@example.com','agent'),
  ('Ilsa','Faust','555-0029','ilsa.faust@example.com','agent'),
  ('Charlie','Babbitt','555-0030','charlie.babbitt@example.com','agent'),
  ('Raymond','Babbitt','555-0031','raymond.babbitt@example.com','agent'),
  ('Jerry','Maguire','555-0032','jerry.maguire@example.com','agent'),
  ('Dorothy','Boyd','555-0033','dorothy.boyd@example.com','agent'),
  ('Rod','Tidwell','555-0034','rod.tidwell@example.com','agent'),
  ('John','Anderton','555-0035','john.anderton@example.com','agent'),
  ('Daniel','Kaffee','555-0036','daniel.kaffee@example.com','agent'),
  ('Nathan','Jessup','555-0037','nathan.jessup@example.com','agent'),
  ('William','Cage','555-0038','william.cage@example.com','agent'),
  ('Rita','Vrataski','555-0039','rita.vrataski@example.com','agent');
